spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/product-manager
    username: root
    password: 700614
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

